# Generated by Django 5.1.5 on 2025-02-28 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='imagen_url',
            field=models.CharField(default='https://img.freepik.com/fotos-premium/foto-3d-mujer-traje-colorido-plumas-coloridas-cabeza_1227606-10209.jpg?w=1380', max_length=300),
        ),
    ]
