# Generated by Django 5.1.5 on 2025-02-28 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0002_evento_imagen_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('imagen_url', models.CharField(default='https://img.freepik.com/psd-premium/disfraces-redes-sociales-tu-carnaval_220664-6324.jpg?w=1380', max_length=300)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
