# Generated by Django 5.1.5 on 2025-02-28 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0003_noticias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_url', models.CharField(default='https://img.freepik.com/psd-premium/carnaval-ofertas-diseno-plantillas-redes-sociales-portugues-brasil-renderizado-3d_364106-3325.jpg?w=360', max_length=300)),
            ],
        ),
    ]
