# Generated by Django 5.1.5 on 2025-02-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0004_imagenes'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenes',
            name='nombre',
            field=models.CharField(default='imagen', max_length=200),
        ),
    ]
