# Generated by Django 5.1.5 on 2025-02-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0005_imagenes_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='imagen_url',
            field=models.CharField(default='https://img.freepik.com/vector-gratis/vector-dos-entradas-cine-disenadas-cerca-vista-superior-aislada-sobre-fondo-blanco_1284-47320.jpg?t=st=1740719910~exp=1740723510~hmac=8aa409fd45d08c6bd3e24325a90f8e69012f7447de506e32b5a404cdde122535&w=1480', max_length=300),
        ),
    ]
