# Generated by Django 5.1.5 on 2025-02-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0006_boleto_imagen_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='descripcion',
            field=models.CharField(default='Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat, cumque. Possimus modi impedit beatae reiciendis at, ab cupiditate. Minus explicabo omnis tempore cumque itaque quas eveniet harum unde similique! Reiciendis?', max_length=300),
        ),
    ]
