# Generated by Django 5.1.5 on 2025-03-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0007_evento_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateField(default='2023-01-01'),
        ),
    ]
