# Generated by Django 5.1.5 on 2025-03-06 22:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0008_producto_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
